CREATE TABLE ID_UTILISATEUR (
    ID_uti INTEGER NOT NULL PRIMARY KEY
);

CREATE TABLE UTILISATEUR (
    mail VARCHAR(25) NOT NULL,
    ID_uti INTEGER NOT NULL,
    mdp VARCHAR(25) NOT NULL,
    nom VARCHAR(25) NOT NULL,
    prenom VARCHAR(25) NOT NULL,
    adresse VARCHAR(100) NOT NULL,
    PRIMARY KEY (mail),
    FOREIGN KEY (ID_uti) REFERENCES ID_UTILISATEUR(ID_uti)
);

CREATE TABLE CATEGORIE (
    nom_cat VARCHAR(25) NOT NULL,
    PRIMARY KEY (nom_cat)
);

CREATE TABLE EST_LA_SOUS_CATEGORIE_DE (
    nom_cat VARCHAR(25) NOT NULL,
    nom_pere VARCHAR(25) NOT NULL,
    PRIMARY KEY (nom_cat),
    FOREIGN KEY (nom_cat) REFERENCES CATEGORIE(nom_cat),
    FOREIGN KEY (nom_pere) REFERENCES CATEGORIE(nom_cat)
);

CREATE TABLE PRODUIT (
    ID_prod INTEGER NOT NULL,
    intitule VARCHAR(25) NOT NULL,
    prix_produit INTEGER NOT NULL CHECK(prix_produit >= 0),
    texte VARCHAR(255) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    nom_cat VARCHAR(25) NOT NULL,
    FOREIGN KEY (nom_cat) REFERENCES CATEGORIE(nom_cat),
    PRIMARY KEY (ID_prod)
);

CREATE TABLE CARACTERISTIQUE (
    ID_prod INTEGER NOT NULL,
    nom_cara VARCHAR(25) NOT NULL,
    valeur VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID_prod, nom_cara),
    FOREIGN KEY (ID_prod) REFERENCES PRODUIT(ID_prod)
);

CREATE TABLE OFFRE (
    ID_prod INTEGER NOT NULL,
    date_heure TIMESTAMP NOT NULL,
    prix INTEGER NOT NULL CHECK(prix >= 0),
    ID_uti INTEGER NOT NULL,
    PRIMARY KEY (ID_prod, date_heure),
    FOREIGN KEY (ID_prod) REFERENCES PRODUIT(ID_prod),
    FOREIGN KEY (ID_uti) REFERENCES ID_UTILISATEUR(ID_uti)
);

CREATE TABLE REMPORTE(
    ID_prod INTEGER NOT NULL,
    date_heure TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_prod),
    FOREIGN KEY (ID_prod) REFERENCES PRODUIT(ID_prod),
    FOREIGN KEY (ID_prod, date_heure) REFERENCES OFFRE(ID_prod, date_heure)
); 
